---
influxdb_base_dir: '/var/lib/influxdb'
influxdb_reporting_disabled: 'true'
influxdb_meta_dir: '{{ influxdb_base_dir }}/meta'
influxdb_data_dir: '{{ influxdb_base_dir }}/data'
influxdb_wal_dir: '{{ influxdb_base_dir }}/wal'
